src/Entity/PvRecettage.php
<?php

namespace App\Entity;

use App\Repository\PvRecettageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PvRecettageRepository::class)]
class PvRecettage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pdf_url = null;

    #[ORM\Column]
    private ?int $version = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $generatedAt = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $technicalEnvironment = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $criticalPoints = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $consequences = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $actionPlan = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $conlusion = null;
    
    /**
     * @var Collection<int, Tests>
     */
    #[ORM\ManyToMany(targetEntity: Tests::class, inversedBy: 'pvRecettages')]
    private Collection $tests;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'pvRecettages')]
    private ?self $PreviousVersion = null;

    /**
     * @var Collection<int, self>
     */
    #[ORM\OneToMany(targetEntity: self::class, mappedBy: 'PreviousVersion')]
    private Collection $pvRecettages;


    public function __construct()
    {
        $this->tests = new ArrayCollection();
        $this->pvRecettages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPdfUrl(): ?string
    {
        return $this->pdf_url;
    }

    public function setPdfUrl(string $pdf_url): static
    {
        $this->pdf_url = $pdf_url;

        return $this;
    }

    public function getVersion(): ?int
    {
        return $this->version;
    }

    public function setVersion(int $version): static
    {
        $this->version = $version;

        return $this;
    }

    public function getGeneratedAt(): ?\DateTimeImmutable
    {
        return $this->generatedAt;
    }

    public function setGeneratedAt(\DateTimeImmutable $generatedAt): static
    {
        $this->generatedAt = $generatedAt;

        return $this;
    }

    /**
     * @return Collection<int, Tests>
     */
    public function getTests(): Collection
    {
        return $this->tests;
    }

    public function addTest(Tests $test): static
    {
        if (!$this->tests->contains($test)) {
            $this->tests->add($test);
        }

        return $this;
    }

    public function removeTest(Tests $test): static
    {
        $this->tests->removeElement($test);

        return $this;
    }

    public function getTechnicalEnvironment(): ?string
    {
        return $this->technicalEnvironment;
    }

    public function setTechnicalEnvironment(?string $technicalEnvironment): static
    {
        $this->technicalEnvironment = $technicalEnvironment;

        return $this;
    }

    public function getCriticalPoints(): ?string
    {
        return $this->criticalPoints;
    }

    public function setCriticalPoints(?string $criticalPoints): static
    {
        $this->criticalPoints = $criticalPoints;

        return $this;
    }

    public function getConsequences(): ?string
    {
        return $this->consequences;
    }

    public function setConsequences(?string $consequences): static
    {
        $this->consequences = $consequences;

        return $this;
    }

    public function getActionPlan(): ?string
    {
        return $this->actionPlan;
    }

    public function setActionPlan(?string $actionPlan): static
    {
        $this->actionPlan = $actionPlan;

        return $this;
    }

    public function getConlusion(): ?string
    {
        return $this->conlusion;
    }

    public function setConlusion(?string $conlusion): static
    {
        $this->conlusion = $conlusion;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPreviousVersion(): ?self
    {
        return $this->PreviousVersion;
    }

    public function setPreviousVersion(?self $PreviousVersion): static
    {
        $this->PreviousVersion = $PreviousVersion;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getPvRecettages(): Collection
    {
        return $this->pvRecettages;
    }

    public function addPvRecettage(self $pvRecettage): static
    {
        if (!$this->pvRecettages->contains($pvRecettage)) {
            $this->pvRecettages->add($pvRecettage);
            $pvRecettage->setPreviousVersion($this);
        }

        return $this;
    }

    public function removePvRecettage(self $pvRecettage): static
    {
        if ($this->pvRecettages->removeElement($pvRecettage)) {
            // set the owning side to null (unless already changed)
            if ($pvRecettage->getPreviousVersion() === $this) {
                $pvRecettage->setPreviousVersion(null);
            }
        }

        return $this;
    }
}

src/Form/PvRecettageType.php
<?php

namespace App\Form;

use App\Entity\PvRecettage;
use App\Entity\Tests;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PvRecettageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom',
                'attr' => ['class' => 'w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none'],
            ])
            ->add('technicalEnvironment', TextareaType::class, [
                'label' => 'Environnement technique',
                'attr' => ['class' => 'w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none'],
            ])
            ->add('criticalPoints', TextareaType::class, [
                'label' => 'Points critiques',
                'attr' => ['class' => 'w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none'],
            ])
            ->add('consequences', TextareaType::class, [
                'label' => 'Conséquences',
                'attr' => ['class' => 'w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none'],
            ])
            ->add('actionPlan', TextareaType::class, [
                'label' => 'Plan d’action',
                'attr' => ['class' => 'w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none'],
            ])
            ->add('conlusion', TextareaType::class, [
                'label' => 'Conclusion',
                'attr' => ['class' => 'w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-400 focus:outline-none'],
            ])
            ->add('tests', EntityType::class, [
                'class' => Tests::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => false,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('t')
                        ->orderBy('t.name', 'ASC');
                },
                'attr' => [
                    'class' => 'select2-multiple w-full',
                    'data-placeholder' => 'Rechercher des tests...',
                ],
                'by_reference' => false,
            ])
            ->add('_token', HiddenType::class, [
                'mapped' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => PvRecettage::class,
            'csrf_protection' => true,
        ]);
    }
}

src/Controller/PvRecettageController.php
<?php

namespace App\Controller;

use App\Entity\PvRecettage;
use App\Form\PvRecettageType;
use App\Repository\PvRecettageRepository;
use App\Service\PdfGenerator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/pv/recettage')]
final class PvRecettageController extends AbstractController
{
    #[Route(name: 'app_pv_recettage_index', methods: ['GET'])]
    public function index(PvRecettageRepository $pvRecettageRepository): Response
    {
        $pvRecettages = $pvRecettageRepository->findAll();
        
        $pvParents = [];
        foreach ($pvRecettages as $pv) {
            if ($pvRecettageRepository->findExistingVersion($pv)) {
                $pvParents[] = $pv->getId();
            }
        }
        return $this->render('pv_recettage/index.html.twig', [
           'pv_recettages' => $pvRecettages,
           'pvParents' => $pvParents, 
        ]);
    }

    #[Route('/new', name: 'app_pv_recettage_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, PdfGenerator $pdfGenerator): Response
    {
        $pvRecettage = new PvRecettage();
        $form = $this->createForm(PvRecettageType::class, $pvRecettage);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pvRecettage->setVersion(1);
            $pvRecettage->setGeneratedAt(new \DateTimeImmutable());
            $entityManager->persist($pvRecettage);
            $entityManager->flush();
            $lastId = $pvRecettage->getId();

            $pdfPath = $pdfGenerator->generatePdf('pv_recettage/pdf.html.twig', [
                'pv' => $pvRecettage
            ], 'pv_recettage_' . $lastId. '.pdf');
            $pvRecettage->setPdfUrl('/pdfs/pv_recettage_' . $lastId . '.pdf');
 
             $entityManager->persist($pvRecettage);
             $entityManager->flush();

            return $this->redirectToRoute('app_pv_recettage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('pv_recettage/new.html.twig', [
            'pv_recettage' => $pvRecettage,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_pv_recettage_show', methods: ['GET'])]
    public function show(PvRecettage $pvRecettage): Response
    {
        return $this->render('pv_recettage/show.html.twig', [
            'pv_recettage' => $pvRecettage,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_pv_recettage_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, PvRecettage $pvRecettage, EntityManagerInterface $entityManager, PvRecettageRepository $pvRecettageRepository, PdfGenerator $pdfGenerator): Response
    {
        // Vérifier si un PV existe déjà avec cet ancêtre
        $existingPv = $pvRecettageRepository->findExistingVersion($pvRecettage);

        if ($existingPv) {
            return $this->redirectToRoute('app_pv_recettage_index');
        }
        $newPv = new PvRecettage();
        $newPv->setVersion($pvRecettage->getVersion() + 1);
        
        // Bind ancien champs
        $newPv->setGeneratedAt(new \DateTimeImmutable());
        $newPv->addPvRecettage($pvRecettage);
        $newPv->setName($pvRecettage->getName());
        $newPv->setTechnicalEnvironment($pvRecettage->getTechnicalEnvironment());
        $newPv->setCriticalPoints($pvRecettage->getCriticalPoints());
        $newPv->setConsequences($pvRecettage->getConsequences());
        $newPv->setActionPlan($pvRecettage->getActionPlan());
        $newPv->setConlusion($pvRecettage->getConlusion());
    
        // 🛠 Copier les tests associés
        foreach ($pvRecettage->getTests() as $test) {
            $newPv->addTest($test);
        }
    
        $form = $this->createForm(PvRecettageType::class, $newPv);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($newPv);
            $entityManager->flush();
           $lastId = $newPv->getId();
            // Générer le PDF
           $pdfPath = $pdfGenerator->generatePdf('pv_recettage/pdf.html.twig', [
               'pv' => $newPv
           ], 'pv_recettage_' . $lastId . '.pdf');
           $newPv->setPdfUrl('/pdfs/pv_recettage_' . $lastId . '.pdf');


            $entityManager->persist($newPv);
            $entityManager->flush();

            return $this->redirectToRoute('app_pv_recettage_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('pv_recettage/edit.html.twig', [
            'pv_recettage' => $pvRecettage,
            'form' => $form,
        ]);
    }

}

templates/pv_recettage/_form.html.twig
{{ form_start(form, {'attr': {'class': 'space-y-4'}}) }}

    <div>
        {{ form_label(form.name, null, {'class': 'block text-sm font-medium text-gray-700'}) }}
        {{ form_widget(form.name) }}
        {{ form_errors(form.name) }}
    </div>

    <div>
        {{ form_label(form.technicalEnvironment, null, {'class': 'block text-sm font-medium text-gray-700'}) }}
        {{ form_widget(form.technicalEnvironment) }}
        {{ form_errors(form.technicalEnvironment) }}
    </div>

    <div>
        {{ form_label(form.criticalPoints, null, {'class': 'block text-sm font-medium text-gray-700'}) }}
        {{ form_widget(form.criticalPoints) }}
        {{ form_errors(form.criticalPoints) }}
    </div>

    <div>
        {{ form_label(form.consequences, null, {'class': 'block text-sm font-medium text-gray-700'}) }}
        {{ form_widget(form.consequences) }}
        {{ form_errors(form.consequences) }}
    </div>

    <div>
        {{ form_label(form.actionPlan, null, {'class': 'block text-sm font-medium text-gray-700'}) }}
        {{ form_widget(form.actionPlan) }}
        {{ form_errors(form.actionPlan) }}
    </div>

    <div>
        {{ form_label(form.conlusion, null, {'class': 'block text-sm font-medium text-gray-700'}) }}
        {{ form_widget(form.conlusion) }}
        {{ form_errors(form.conlusion) }}
    </div>

    {# Sélection des tests avec recherche #}
    <div>
        {{ form_label(form.tests, null, {'class': 'block text-sm font-medium text-gray-700'}) }}
        {{ form_widget(form.tests, {'attr': {'class': 'select2-multiple w-full'}}) }}
        {{ form_errors(form.tests) }}
    </div>
    
    {{ form_row(form._token) }}
    <div class="mt-6 flex justify-end">
            <div class="flex gap-2">
                <button type="submit" class="w-full px-4 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-700">{{ button_label|default('Créer le PV') }}</button>
            </div>
        </div>
{{ form_end(form) }}

templates/pv_recettage/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit PvRecettage{% endblock %}

{% block body %}
    <div class="max-w-2xl mx-auto mt-10 p-6 bg-white shadow-lg rounded-2xl">
        <div class="flex justify-between">
            <h2 class="text-2xl font-semibold text-gray-900 mb-6 text-center">Mettre à jour un PV</h2>
            <a href="{{ path('app_pv_recettage_index') }}" class="inline-block mb-4 text-blue-600 hover:underline">← Retour à la liste</a>
        </div>
        {{ include('pv_recettage/_form.html.twig', {'button_label': 'Mettre à jour', 'delete_form': true}) }}
    </div>
{% endblock %}

templates/pv_recettage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}PvRecettage index{% endblock %}

{% block body %}
    <div class="max-w-6xl mx-auto mt-10 p-6 bg-white shadow-lg rounded-2xl">
        <h1 class="text-3xl font-semibold text-gray-900 mb-6 text-center">Liste des PvRecettages</h1>

        <div class="mb-4 text-right">
            <a href="{{ path('app_pv_recettage_new') }}" class="px-4 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-700">Créer un nouveau PvRecettage</a>
        </div>

        <div class="overflow-hidden shadow-md rounded-lg">
            <table class="w-full border-collapse">
                <thead>
                    <tr class="bg-gray-100">
                        <th class="p-4 text-left text-gray-700">Nom</th>
                        <th class="p-4 text-left text-gray-700">Version</th>
                        <th class="p-4 text-left text-gray-700">Généré le</th>
                        <th class="p-4 text-left text-gray-700">Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for pv_recettage in pv_recettages %}
                    <tr class="border-b">
                        <td class="p-4">{{ pv_recettage.name }}</td>
                        <td class="p-4">{{ pv_recettage.version }}</td>
                        <td class="p-4">{{ pv_recettage.generatedAt ? pv_recettage.generatedAt|date('Y-m-d H:i:s') : '' }}</td>
                       <td class="p-4 flex space-x-2">
                           <a href="{{ pv_recettage.pdfUrl }}" target="_blank" class="px-4 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-700">Voir</a>
                            {% if pv_recettage.id not in pvParents %}
                                <a href="{{ path('app_pv_recettage_edit', {'id': pv_recettage.id}) }}" class="px-4 py-2 text-white bg-yellow-600 rounded-lg hover:bg-yellow-700">Modifier</a>
                            {% endif %}
                        </td>

                    </tr>
                {% else %}
                    <tr>
                        <td colspan="4" class="p-4 text-center text-gray-500">Aucun PvRecettage trouvé</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/pv_recettage/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New PvRecettage{% endblock %}

{% block body %}
    <div class="max-w-2xl mx-auto mt-10 p-6 bg-white shadow-lg rounded-2xl">
            <div class="flex justify-between">
                <h2 class="text-2xl font-semibold text-gray-900 mb-6 text-center">Créer un nouveau Pv de recettage</h2>
                <a href="{{ path('app_pv_recettage_index') }}" class="inline-block mb-4 text-blue-600 hover:underline">← Retour à la liste</a>
            </div>
        {{ include('pv_recettage/_form.html.twig', {'delete_form': false}) }}
    </div>
{% endblock %}

templates/pv_recettage/pdf.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; }
        .container { width: 100%; padding: 20px; }
        h1 { text-align: center; }
        .section { margin-bottom: 20px; }
        .section h2 { border-bottom: 1px solid #000; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 10px; border: 1px solid #ddd; }
    </style>
</head>
<body>
    <div class="container">
        <h1>PV Recettage - {{ pv.name }}</h1>

        <div class="section">
            <h2>Environnement technique</h2>
            <p>{{ pv.technicalEnvironment }}</p>
        </div>
        <div class="section">
            <h2>Points critiques</h2>
            <p>{{ pv.criticalPoints }}</p>
        </div>
        <div class="section">
            <h2>Conséquences</h2>
            <p>{{ pv.consequences }}</p>
        </div>
        <div class="section">
            <h2>Plan d’action</h2>
            <p>{{ pv.actionPlan }}</p>
        </div>
        <div class="section">
            <h2>Conclusion</h2>
            <p>{{ pv.conlusion }}</p>
        </div>

        <div class="section">
            <h2>Tests associés</h2>
            <table>
                <thead>
                   <tr class="bg-gray-100">
                        <th class="p-4 text-left text-gray-700">Nom</th>
                        <th class="p-4 text-left text-gray-700">Statut</th>
                        <th class="p-4 text-left text-gray-700">Créé le</th>
                        <th class="p-4 text-left text-gray-700">Etapes</th>
                    </tr>
                </thead>
                <tbody>
                {% for test in pv.tests %}
                    <tr>
                        <td class="p-4">{{ test.name }}</td>
                        <td class="p-4">
                            {% if test.status == 'en_cours' %}
                                <span class="px-3 py-1 text-orange-700 bg-orange-100 border border-orange-500 rounded-lg whitespace-nowrap">En cours</span>
                            {% elseif test.status == 'reussi' %}
                                <span class="px-3 py-1 text-green-700 bg-green-100 border border-green-500 rounded-lg">Réussi</span>
                            {% elseif test.status == 'echoue' %}
                                <span class="px-3 py-1 text-red-700 bg-red-100 border border-red-500 rounded-lg">Échoué</span>
                            {% endif %}
                        </td>
                        <td class="p-4">{{ test.createdAt ? test.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td class="p-4">{{ test.steps }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="2" class="text-center">Aucun test associé</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

templates/pv_recettage/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}PvRecettage{% endblock %}

{% block body %}
    <h1>PvRecettage</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ pv_recettage.id }}</td>
            </tr>
            <tr>
                <th>Pdf_url</th>
                <td>{{ pv_recettage.pdfUrl }}</td>
            </tr>
            <tr>
                <th>Version</th>
                <td>{{ pv_recettage.version }}</td>
            </tr>
            <tr>
                <th>GeneratedAt</th>
                <td>{{ pv_recettage.generatedAt ? pv_recettage.generatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>TechnicalEnvironment</th>
                <td>{{ pv_recettage.technicalEnvironment }}</td>
            </tr>
            <tr>
                <th>CriticalPoints</th>
                <td>{{ pv_recettage.criticalPoints }}</td>
            </tr>
            <tr>
                <th>Consequences</th>
                <td>{{ pv_recettage.consequences }}</td>
            </tr>
            <tr>
                <th>ActionPlan</th>
                <td>{{ pv_recettage.actionPlan }}</td>
            </tr>
            <tr>
                <th>Conlusion</th>
                <td>{{ pv_recettage.conlusion }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_pv_recettage_index') }}">back to list</a>

    <a href="{{ path('app_pv_recettage_edit', {'id': pv_recettage.id}) }}">edit</a>

{% endblock %}